Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -21,22 +21,33 @@ jobs:
         with:
           go-version: '1.21'
 
-      - name: Install Cosign (official binary)
-        run: |
-          wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
-          chmod +x cosign-linux-amd64
-          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
+      # - name: Install Cosign (official binary)
+      #   run: |
+      #     wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
+      #     chmod +x cosign-linux-amd64
+      #     sudo mv cosign-linux-amd64 /usr/local/bin/cosign
 
-      - name: Compile Cosign (from source, with PKCS#11 support)
+      # - name: Compile Cosign (from source, with PKCS#11 support)
+      #   run: |
+      #     git clone https://github.com/sigstore/cosign.git
+      #     cd cosign
+      #     go build -tags=pkcs11key -o cosign ./cmd/cosign
+      #     sudo mv cosign /usr/local/bin/cosign
+
+      # - name: Check Cosign version and PKCS#11 support
+      #   env:
+      #     COSIGN_PKCS11: "true"
+      #   run: |
+      #     cosign version
+      #     cosign sign --help | grep -i pkcs11 || echo "PKCS#11 support not found"
+
+      - name: Download Cosign with PKCS#11 support
         run: |
-          git clone https://github.com/sigstore/cosign.git
-          cd cosign
-          go build -tags=pkcs11key -o cosign ./cmd/cosign
+          # For Linux AMD64
+          wget -O cosign https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-pivkey-pkcs11key-amd64
+          chmod +x cosign
           sudo mv cosign /usr/local/bin/cosign
-
-      - name: Check Cosign version and PKCS#11 support
-        env:
-          COSIGN_PKCS11: "true"
-        run: |
+          
+          # Verify
           cosign version
-          cosign sign --help | grep -i pkcs11 || echo "PKCS#11 support not found"
+          cosign pkcs11-tool --help | head -3      
